// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from "dotenv";
import { fileURLToPath } from "url";
import { dirname, resolve } from "path";
import { defineConfig } from "prisma/config";

// Load the project's .env file relative to this config file so Prisma
// receives DATABASE_URL even when the CLI runs from a different cwd.
// const __dirname = dirname(fileURLToPath(import.meta.url));
// dotenv.config({ path: resolve(__dirname, ".env") });

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: process.env["DATABASE_URL"],
//   },
// });
